import { createHash } from "node:crypto";
import { exists, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { Paths } from "../constants";
import { ok, type Result } from "../types";
import { readWorkspaceConfig } from "./config";
import { type GitEnv, getDefaultBranch } from "./git";
import { toSlug } from "./slug";

async function hashFileContent(filePath: string): Promise<string | null> {
  try {
    const content = await readFile(filePath);
    if (content.length === 0) {
      return null;
    }
    return createHash("sha256").update(content).digest("hex");
  } catch {
    return null;
  }
}

export interface WorkspaceAgentTreeEntry {
  repo: string;
  slug: string;
  hash: string;
}

export interface GenerateAgentFilesResult {
  treesMd: WorkspaceAgentTreeEntry[];
  claudeMd: "created" | "exists";
  agentsMd: "created" | "exists";
}

async function ensureWorkspaceEntryFile(
  filePath: string,
  content: string,
): Promise<"created" | "exists"> {
  if (await exists(filePath)) {
    return "exists";
  }

  await writeFile(filePath, content);
  return "created";
}

export async function generateAgentFiles(
  workspace: string,
  paths: Paths,
  env?: GitEnv,
): Promise<Result<GenerateAgentFilesResult>> {
  const configResult = await readWorkspaceConfig(workspace, paths);
  if (!configResult.ok) {
    return configResult;
  }

  const { repos } = configResult.value;

  // Ensure .claude/ dir exists
  await mkdir(paths.workspaceClaudeDir(workspace), { recursive: true });

  // Build entries for repos that have a CLAUDE.md in any worktree, with per-repo dedup
  const treesMdLines = ["# Generated by grove — do not edit manually"];
  const included: WorkspaceAgentTreeEntry[] = [];
  const sortedRepos = repos.slice().sort((a, b) => a.name.localeCompare(b.name));

  for (const repo of sortedRepos) {
    // Determine default branch (null if unavailable — don't skip repo)
    let defaultSlug: string | null = null;
    try {
      const branchResult = await getDefaultBranch(repo.path, env);
      if (branchResult.ok) {
        defaultSlug = toSlug(branchResult.value);
      }
    } catch {
      // leave defaultSlug as null
    }

    // Discover all worktree slugs from disk
    let diskSlugs: string[];
    try {
      const dirents = await readdir(paths.repoDir(workspace, repo.name), {
        withFileTypes: true,
      });
      diskSlugs = dirents.filter((d) => d.isDirectory() || d.isSymbolicLink()).map((d) => d.name);
    } catch {
      continue; // trees/{repo}/ doesn't exist — skip
    }

    // Order: default slug first (if present), then rest alphabetically
    const orderedSlugs =
      defaultSlug !== null && diskSlugs.includes(defaultSlug)
        ? [
            defaultSlug,
            ...diskSlugs.filter((s) => s !== defaultSlug).sort((a, b) => a.localeCompare(b)),
          ]
        : diskSlugs.slice().sort((a, b) => a.localeCompare(b));

    // Hash all slugs concurrently; results are in orderedSlugs order so canonical priority is preserved
    const hashes = await Promise.all(
      orderedSlugs.map((slug) =>
        hashFileContent(join(paths.worktreeDir(workspace, repo.name, slug), "CLAUDE.md")),
      ),
    );

    // Group slugs by content hash: first slug per group is canonical, rest are deduped
    const hashGroups = new Map<string, string[]>();
    for (const [slug, hash] of orderedSlugs.map((s, i) => [s, hashes[i]] as const)) {
      if (hash === null) {
        continue;
      }
      const group = hashGroups.get(hash);
      if (group) {
        group.push(slug);
      } else {
        hashGroups.set(hash, [slug]);
      }
    }

    for (const [hash, slugs] of hashGroups) {
      const canonical = slugs[0];
      const deduped = slugs.slice(1);
      const annotation = deduped.length > 0 ? ` (also: ${deduped.join(", ")})` : "";
      treesMdLines.push(`# ${repo.name}/${canonical}${annotation}`);
      treesMdLines.push(`@../trees/${repo.name}/${canonical}/CLAUDE.md`);
      included.push({ repo: repo.name, slug: canonical, hash });
    }
  }

  const treesMdContent = `${treesMdLines.join("\n")}\n`;

  await writeFile(paths.claudeTreesMd(workspace), treesMdContent);

  const claudeMdStatus = await ensureWorkspaceEntryFile(
    paths.claudeMd(workspace),
    "@.claude/trees.md\n",
  );
  const agentsMdStatus = await ensureWorkspaceEntryFile(
    paths.agentsMd(workspace),
    "@.claude/trees.md\n",
  );

  return ok({ treesMd: included, claudeMd: claudeMdStatus, agentsMd: agentsMdStatus });
}
