import { entries } from "./errors";

const HEADER = `<!-- Generated by scripts/gen-errors.ts. Do not edit by hand. Regenerate with \`bun run gen:errors\`. -->

# Grove error codes

Every error returned by grove carries a SCREAMING_SNAKE_CASE code. The codes below are the canonical set; see \`src/lib/errors.ts\` for the source.
`;

export function renderErrorsMarkdown(): string {
  const sections = entries()
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([code, entry]) => {
      const hint = entry.hint ? `\n\n**Hint:** ${entry.hint}` : "";
      return `## ${code}\n\n${entry.description}${hint}`;
    });
  return `${HEADER}\n${sections.join("\n\n")}\n`;
}
