import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import { existsSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { createPaths } from "../../constants";
import { generateClaudeFiles } from "../../lib/claude";
import { writeConfig } from "../../lib/config";
import { cleanup, createTestDir, createTestGitRepo, GIT_ENV } from "../helpers";

describe("generateClaudeFiles", () => {
  let tempDir: string;
  let paths: ReturnType<typeof createPaths>;

  beforeEach(async () => {
    tempDir = await createTestDir();
    paths = createPaths(join(tempDir, "workspaces"));
  });

  afterEach(() => {
    cleanup(tempDir);
  });

  /** Create workspace dir, .claude dir, and workspace.json */
  async function setupWorkspace(ws: string, repos: { name: string; path: string }[] = []) {
    await mkdir(paths.workspace(ws), { recursive: true });
    await mkdir(paths.workspaceClaudeDir(ws), { recursive: true });
    await writeConfig(paths.workspaceConfig(ws), { name: ws, repos });
  }

  /**
   * Create a real git repo, wire up trees/{repo}/{slug} symlink,
   * and optionally write a CLAUDE.md into the repo.
   */
  async function setupRepo(
    ws: string,
    name: string,
    opts: { defaultBranch?: string; hasClaude?: boolean } = {},
  ): Promise<string> {
    const { defaultBranch = "main", hasClaude = true } = opts;
    const repoPath = await createTestGitRepo(tempDir, name, defaultBranch);

    // Create trees/{repo}/ dir and symlink trees/{repo}/{slug} -> repo
    const repoDir = paths.repoDir(ws, name);
    await mkdir(repoDir, { recursive: true });
    const slug = defaultBranch.replaceAll("/", "-");
    symlinkSync(repoPath, paths.worktreeDir(ws, name, slug));

    if (hasClaude) {
      writeFileSync(join(repoPath, "CLAUDE.md"), `# ${name}\nProject docs.\n`);
    }

    return repoPath;
  }

  // ── trees.md generation ─────────────────────────────────────────

  describe("trees.md generation", () => {
    it("generates trees.md with @references for repos that have CLAUDE.md", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const pathB = await setupRepo("ws", "bravo");
      await setupWorkspace("ws", [
        { name: "alpha", path: pathA },
        { name: "bravo", path: pathB },
      ]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([
        { repo: "alpha", slug: "main", hash: expect.any(String) },
        { repo: "bravo", slug: "main", hash: expect.any(String) },
      ]);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).toContain("@../trees/alpha/main/CLAUDE.md");
      expect(content).toContain("@../trees/bravo/main/CLAUDE.md");
    });

    it("skips repos whose worktree has no CLAUDE.md", async () => {
      const pathA = await setupRepo("ws", "alpha", { hasClaude: true });
      const pathB = await setupRepo("ws", "bravo", { hasClaude: false });
      await setupWorkspace("ws", [
        { name: "alpha", path: pathA },
        { name: "bravo", path: pathB },
      ]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([
        { repo: "alpha", slug: "main", hash: expect.any(String) },
      ]);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).toContain("@../trees/alpha/main/CLAUDE.md");
      expect(content).not.toContain("bravo");
    });

    it("generates trees.md with header but no @references when no repos have CLAUDE.md", async () => {
      const pathA = await setupRepo("ws", "alpha", { hasClaude: false });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([]);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).not.toContain("@");
      expect(content).toContain("Generated by grove");
    });

    it("sorts references alphabetically by repo name", async () => {
      const pathZ = await setupRepo("ws", "zebra");
      const pathA = await setupRepo("ws", "apple");
      const pathM = await setupRepo("ws", "mango");
      await setupWorkspace("ws", [
        { name: "zebra", path: pathZ },
        { name: "apple", path: pathA },
        { name: "mango", path: pathM },
      ]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([
        { repo: "apple", slug: "main", hash: expect.any(String) },
        { repo: "mango", slug: "main", hash: expect.any(String) },
        { repo: "zebra", slug: "main", hash: expect.any(String) },
      ]);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      const lines = content.split("\n").filter((l) => l.startsWith("@"));
      expect(lines[0]).toContain("apple");
      expect(lines[1]).toContain("mango");
      expect(lines[2]).toContain("zebra");
    });

    it("uses slugified branch in path", async () => {
      const pathA = await setupRepo("ws", "alpha", {
        defaultBranch: "release/1.0",
      });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd[0].slug).toBe("release-1.0");
      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).toContain("@../trees/alpha/release-1.0/CLAUDE.md");
    });

    it("handles multi-level branch slugification", async () => {
      const pathA = await setupRepo("ws", "alpha", {
        defaultBranch: "feature/team/task-123",
      });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).toContain("@../trees/alpha/feature-team-task-123/CLAUDE.md");
    });

    it("generates trees.md for empty workspace", async () => {
      await setupWorkspace("ws");

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([]);
      expect(existsSync(paths.claudeTreesMd("ws"))).toBe(true);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).toContain("Generated by grove");
    });

    it("overwrites existing trees.md on regeneration", async () => {
      const pathA = await setupRepo("ws", "alpha");
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      writeFileSync(paths.claudeTreesMd("ws"), "stale content\n");

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).not.toContain("stale content");
      expect(content).toContain("@../trees/alpha/main/CLAUDE.md");
    });

    it("emits each @reference on its own line", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const pathB = await setupRepo("ws", "bravo");
      await setupWorkspace("ws", [
        { name: "alpha", path: pathA },
        { name: "bravo", path: pathB },
      ]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      const atLines = content.split("\n").filter((l) => l.startsWith("@"));
      expect(atLines).toHaveLength(2);
      expect(atLines[0]).toBe("@../trees/alpha/main/CLAUDE.md");
      expect(atLines[1]).toBe("@../trees/bravo/main/CLAUDE.md");
    });
  });

  // ── CLAUDE.md creation ──────────────────────────────────────────

  describe("CLAUDE.md creation", () => {
    it("creates CLAUDE.md when it does not exist", async () => {
      await setupWorkspace("ws");

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.claudeMd).toBe("created");

      const content = readFileSync(paths.claudeMd("ws"), "utf-8");
      expect(content).toContain("@.claude/trees.md");
    });

    it("does not overwrite existing CLAUDE.md", async () => {
      await setupWorkspace("ws");
      writeFileSync(paths.claudeMd("ws"), "# My custom workspace notes\n@.claude/trees.md\n");

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.claudeMd).toBe("exists");

      const content = readFileSync(paths.claudeMd("ws"), "utf-8");
      expect(content).toBe("# My custom workspace notes\n@.claude/trees.md\n");
    });

    it("is idempotent across both files", async () => {
      const pathA = await setupRepo("ws", "alpha");
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result1 = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result1.ok).toBe(true);
      const claudeMd1 = readFileSync(paths.claudeMd("ws"), "utf-8");
      const treesMd1 = readFileSync(paths.claudeTreesMd("ws"), "utf-8");

      const result2 = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result2.ok).toBe(true);
      const claudeMd2 = readFileSync(paths.claudeMd("ws"), "utf-8");
      const treesMd2 = readFileSync(paths.claudeTreesMd("ws"), "utf-8");

      expect(claudeMd1).toBe(claudeMd2);
      expect(treesMd1).toBe(treesMd2);
    });
  });

  // ── error handling ──────────────────────────────────────────────

  describe("error handling", () => {
    it("returns WORKSPACE_NOT_FOUND for non-existent workspace", async () => {
      const result = await generateClaudeFiles("ghost", paths, GIT_ENV);
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.code).toBe("WORKSPACE_NOT_FOUND");
      }
    });

    it("skips repos with dangling source path", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const pathB = await setupRepo("ws", "bravo");
      await setupWorkspace("ws", [
        { name: "alpha", path: pathA },
        { name: "bravo", path: pathB },
      ]);

      // Delete bravo's source repo
      rmSync(pathB, { recursive: true, force: true });

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([
        { repo: "alpha", slug: "main", hash: expect.any(String) },
      ]);
    });

    it("includes no entries when getDefaultBranch fails and trees dir is empty", async () => {
      const pathA = await setupRepo("ws", "alpha");

      // Create a repo with detached HEAD using the .git/HEAD write pattern
      const detachedPath = join(tempDir, "bravo");
      await mkdir(detachedPath, { recursive: true });
      const gitEnv = {
        ...process.env,
        ...GIT_ENV,
        HOME: tempDir,
      };
      Bun.spawnSync(["git", "init", "-b", "main", detachedPath], {
        env: gitEnv,
      });
      Bun.spawnSync(["git", "-C", detachedPath, "config", "user.email", "test@test.com"], {
        env: gitEnv,
      });
      Bun.spawnSync(["git", "-C", detachedPath, "config", "user.name", "Test"], { env: gitEnv });
      writeFileSync(join(detachedPath, "README"), "x");
      Bun.spawnSync(["git", "-C", detachedPath, "add", "."], { env: gitEnv });
      Bun.spawnSync(["git", "-C", detachedPath, "commit", "-m", "init"], {
        env: gitEnv,
      });
      const shaResult = Bun.spawnSync(["git", "-C", detachedPath, "rev-parse", "HEAD"], {
        env: gitEnv,
      });
      const sha = new TextDecoder().decode(shaResult.stdout).trim();
      writeFileSync(join(detachedPath, ".git", "HEAD"), `${sha}\n`);

      writeFileSync(join(detachedPath, "CLAUDE.md"), "# bravo\n");

      // Set up tree dir but no slug symlink (can't determine branch)
      await mkdir(paths.repoDir("ws", "bravo"), { recursive: true });

      await setupWorkspace("ws", [
        { name: "alpha", path: pathA },
        { name: "bravo", path: detachedPath },
      ]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([
        { repo: "alpha", slug: "main", hash: expect.any(String) },
      ]);
    });

    it("still scans worktrees when getDefaultBranch fails", async () => {
      const pathA = await setupRepo("ws", "alpha");

      // Create a detached HEAD repo so getDefaultBranch fails
      const detachedPath = join(tempDir, "bravo");
      await mkdir(detachedPath, { recursive: true });
      const gitEnv = { ...process.env, ...GIT_ENV, HOME: tempDir };
      Bun.spawnSync(["git", "init", "-b", "main", detachedPath], {
        env: gitEnv,
      });
      Bun.spawnSync(["git", "-C", detachedPath, "config", "user.email", "test@test.com"], {
        env: gitEnv,
      });
      Bun.spawnSync(["git", "-C", detachedPath, "config", "user.name", "Test"], { env: gitEnv });
      writeFileSync(join(detachedPath, "README"), "x");
      Bun.spawnSync(["git", "-C", detachedPath, "add", "."], { env: gitEnv });
      Bun.spawnSync(["git", "-C", detachedPath, "commit", "-m", "init"], {
        env: gitEnv,
      });
      const shaResult = Bun.spawnSync(["git", "-C", detachedPath, "rev-parse", "HEAD"], {
        env: gitEnv,
      });
      const sha = new TextDecoder().decode(shaResult.stdout).trim();
      writeFileSync(join(detachedPath, ".git", "HEAD"), `${sha}\n`);

      // Set up a worktree slug with a CLAUDE.md so scanning can find it
      await setupWorktreeEntry("ws", "bravo", "feature-1", {
        claudeContent: "# bravo feature\n",
      });

      await setupWorkspace("ws", [
        { name: "alpha", path: pathA },
        { name: "bravo", path: detachedPath },
      ]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual(
        expect.arrayContaining([
          { repo: "alpha", slug: "main", hash: expect.any(String) },
          { repo: "bravo", slug: "feature-1", hash: expect.any(String) },
        ]),
      );
    });

    it("creates .claude directory if missing", async () => {
      await setupWorkspace("ws");
      // Remove the .claude/ dir that setupWorkspace created
      rmSync(paths.workspaceClaudeDir("ws"), { recursive: true, force: true });

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      expect(existsSync(paths.claudeTreesMd("ws"))).toBe(true);
    });
  });

  /**
   * Create a plain directory with an optional CLAUDE.md and symlink it
   * into trees/{repo}/{slug}. Does NOT create a git repo.
   */
  async function setupWorktreeEntry(
    ws: string,
    repo: string,
    slug: string,
    opts: { claudeContent?: string } = {},
  ): Promise<string> {
    const wtDir = join(tempDir, `worktree-${repo}-${slug}`);
    await mkdir(wtDir, { recursive: true });
    if (opts.claudeContent !== undefined) {
      writeFileSync(join(wtDir, "CLAUDE.md"), opts.claudeContent);
    }
    await mkdir(paths.repoDir(ws, repo), { recursive: true });
    symlinkSync(wtDir, paths.worktreeDir(ws, repo, slug));
    return wtDir;
  }

  // ── trees.md comment lines ───────────────────────────────────────

  describe("trees.md comment lines", () => {
    it("emits # repo/slug comment line immediately before each @reference", async () => {
      const pathA = await setupRepo("ws", "alpha");
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      const fileLines = content.split("\n");
      const atIdx = fileLines.indexOf("@../trees/alpha/main/CLAUDE.md");
      expect(atIdx).toBeGreaterThan(0);
      expect(fileLines[atIdx - 1]).toBe("# alpha/main");
    });

    it("does not emit hash lines in trees.md", async () => {
      const pathA = await setupRepo("ws", "alpha");
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).not.toContain("sha256");
    });

    it("preserves the generated-by header as the first line", async () => {
      await setupWorkspace("ws");

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content.split("\n")[0]).toBe("# Generated by grove — do not edit manually");
    });
  });

  // ── hash correctness ─────────────────────────────────────────────

  describe("hash correctness", () => {
    it("returns deterministic sha256 hash for known file content", async () => {
      const knownContent = "# alpha\nProject docs.\n";
      const expectedHash = "0dd6d04f03204a51ec791f0f7369273268f896eba8e3a45fe64c3f5864f3305b";
      const pathA = await setupRepo("ws", "alpha");
      // Overwrite CLAUDE.md with known content
      writeFileSync(join(pathA, "CLAUDE.md"), knownContent);
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd[0].hash).toBe(expectedHash);
    });

    it("skips worktree when CLAUDE.md is empty", async () => {
      const pathA = await setupRepo("ws", "alpha");
      // Overwrite with empty file
      writeFileSync(join(pathA, "CLAUDE.md"), "");
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([]);
    });
  });

  // ── worktree scanning (4a) ────────────────────────────────────────

  describe("worktree scanning", () => {
    it("includes feature branch when default branch has no CLAUDE.md", async () => {
      const pathA = await setupRepo("ws", "alpha", { hasClaude: false });
      await setupWorktreeEntry("ws", "alpha", "feature-x", {
        claudeContent: "# feature-x\n",
      });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd).toEqual([
        { repo: "alpha", slug: "feature-x", hash: expect.any(String) },
      ]);
    });

    it("orders non-default slugs alphabetically after default branch", async () => {
      const pathA = await setupRepo("ws", "alpha");
      await setupWorktreeEntry("ws", "alpha", "z-branch", {
        claudeContent: "# z\n",
      });
      await setupWorktreeEntry("ws", "alpha", "a-branch", {
        claudeContent: "# a\n",
      });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd.map((e) => e.slug)).toEqual(["main", "a-branch", "z-branch"]);
    });

    it("orders all slugs alphabetically when default branch not in trees dir", async () => {
      const pathA = await setupRepo("ws", "alpha", { hasClaude: false });
      // Remove the default branch entry so diskSlugs truly excludes defaultSlug
      rmSync(paths.worktreeDir("ws", "alpha", "main"));
      await setupWorktreeEntry("ws", "alpha", "z-feat", {
        claudeContent: "# z\n",
      });
      await setupWorktreeEntry("ws", "alpha", "a-feat", {
        claudeContent: "# a\n",
      });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd.map((e) => e.slug)).toEqual(["a-feat", "z-feat"]);
    });

    it("gracefully skips repo when trees directory does not exist", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const pathB = await setupRepo("ws", "bravo");
      await setupWorkspace("ws", [
        { name: "alpha", path: pathA },
        { name: "bravo", path: pathB },
      ]);

      // Remove bravo's trees directory entirely
      rmSync(paths.repoDir("ws", "bravo"), { recursive: true, force: true });

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd.map((e) => e.repo)).toEqual(["alpha"]);
    });
  });

  // ── deduplication (4b) ────────────────────────────────────────────

  describe("worktree deduplication", () => {
    it("includes feature branch when content differs from default", async () => {
      const pathA = await setupRepo("ws", "alpha");
      await setupWorktreeEntry("ws", "alpha", "feature-x", {
        claudeContent: "# different\n",
      });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd.map((e) => e.slug)).toEqual(["main", "feature-x"]);
    });

    it("deduplicates feature branch when content is identical to default", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const claudeContent = readFileSync(join(pathA, "CLAUDE.md"), "utf-8");
      await setupWorktreeEntry("ws", "alpha", "feature-x", { claudeContent });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd.map((e) => e.slug)).toEqual(["main"]);
    });

    it("default branch wins over alphabetically-earlier slug with same content", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const claudeContent = readFileSync(join(pathA, "CLAUDE.md"), "utf-8");
      await setupWorktreeEntry("ws", "alpha", "aaa-first", { claudeContent });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd.map((e) => e.slug)).toEqual(["main"]);
    });

    it("includes unique branches and deduplicates identical ones", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const claudeContent = readFileSync(join(pathA, "CLAUDE.md"), "utf-8");
      await setupWorktreeEntry("ws", "alpha", "feat-a", { claudeContent }); // same
      await setupWorktreeEntry("ws", "alpha", "feat-b", {
        claudeContent: "# different\n",
      }); // different
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd.map((e) => e.slug)).toEqual(["main", "feat-b"]);
    });

    it("does not deduplicate identical content across different repos", async () => {
      const sharedContent = "# shared content\n";
      const pathA = await setupRepo("ws", "alpha");
      writeFileSync(join(pathA, "CLAUDE.md"), sharedContent);
      const pathB = await setupRepo("ws", "bravo");
      writeFileSync(join(pathB, "CLAUDE.md"), sharedContent);
      await setupWorkspace("ws", [
        { name: "alpha", path: pathA },
        { name: "bravo", path: pathB },
      ]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd.map((e) => e.repo)).toEqual(["alpha", "bravo"]);
    });

    it("emits dedup annotation in trees.md comment for identical slugs", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const claudeContent = readFileSync(join(pathA, "CLAUDE.md"), "utf-8");
      await setupWorktreeEntry("ws", "alpha", "feat-a", { claudeContent });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      await generateClaudeFiles("ws", paths, GIT_ENV);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).toContain("# alpha/main (also: feat-a)");
    });

    it("sorts multiple deduped slugs alphabetically in annotation", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const claudeContent = readFileSync(join(pathA, "CLAUDE.md"), "utf-8");
      await setupWorktreeEntry("ws", "alpha", "zzz-last", { claudeContent });
      await setupWorktreeEntry("ws", "alpha", "aaa-first", { claudeContent });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      await generateClaudeFiles("ws", paths, GIT_ENV);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).toContain("# alpha/main (also: aaa-first, zzz-last)");
    });

    it("emits no annotation when no slugs are deduplicated", async () => {
      const pathA = await setupRepo("ws", "alpha");
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      await generateClaudeFiles("ws", paths, GIT_ENV);

      const content = readFileSync(paths.claudeTreesMd("ws"), "utf-8");
      expect(content).toContain("# alpha/main");
      expect(content).not.toContain("(also:");
    });

    it("does not expose deduped field in return value", async () => {
      const pathA = await setupRepo("ws", "alpha");
      const claudeContent = readFileSync(join(pathA, "CLAUDE.md"), "utf-8");
      await setupWorktreeEntry("ws", "alpha", "feat-a", { claudeContent });
      await setupWorkspace("ws", [{ name: "alpha", path: pathA }]);

      const result = await generateClaudeFiles("ws", paths, GIT_ENV);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.treesMd[0]).not.toHaveProperty("deduped");
    });
  });
});
