import { describe, expect, it } from "bun:test";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import type { ErrorEntry } from "../../lib/errors";
import { ERROR_CATALOG, mapFsError, renderErrorsMarkdown } from "../../lib/errors";

describe("ERROR_CATALOG", () => {
  it("has unique codes (object keys are inherently unique, but verify the type matches)", () => {
    const codes = Object.keys(ERROR_CATALOG);
    expect(new Set(codes).size).toBe(codes.length);
  });

  it("has a non-empty description for every entry", () => {
    for (const [code, entry] of Object.entries(ERROR_CATALOG)) {
      expect(entry.description, `${code} description`).toBeTruthy();
      expect(entry.description.length, `${code} description length`).toBeGreaterThan(0);
    }
  });
});

describe("renderErrorsMarkdown", () => {
  it("includes a heading for every error code in alphabetical order", () => {
    const md = renderErrorsMarkdown();
    const codes = Object.keys(ERROR_CATALOG).sort();
    for (const code of codes) {
      expect(md).toContain(`## ${code}`);
    }
    // Verify alphabetical order by checking index positions are monotonically increasing
    let lastIndex = -1;
    for (const code of codes) {
      const idx = md.indexOf(`## ${code}`);
      expect(idx, `## ${code} should appear after previous code`).toBeGreaterThan(lastIndex);
      lastIndex = idx;
    }
  });

  it("includes the description for each code", () => {
    const md = renderErrorsMarkdown();
    for (const [code, entry] of Object.entries(ERROR_CATALOG)) {
      expect(md, `description for ${code}`).toContain(entry.description);
    }
  });

  it("includes the hint when present", () => {
    const md = renderErrorsMarkdown();
    for (const [code, entry] of Object.entries(ERROR_CATALOG) as [string, ErrorEntry][]) {
      if (entry.hint) {
        expect(md, `hint for ${code}`).toContain(`**Hint:** ${entry.hint}`);
      }
    }
  });

  it("does not include a Hint line for codes without a hint", () => {
    const md = renderErrorsMarkdown();
    const codesWithoutHint = (Object.entries(ERROR_CATALOG) as [string, ErrorEntry][])
      .filter(([, entry]) => !entry.hint)
      .map(([code]) => code);
    // Every ## SECTION for codes without a hint should not be followed by a Hint line
    // before the next ## heading
    for (const code of codesWithoutHint) {
      const headingPos = md.indexOf(`## ${code}\n`);
      const nextHeadingPos = md.indexOf("\n## ", headingPos + 1);
      const section =
        nextHeadingPos === -1 ? md.slice(headingPos) : md.slice(headingPos, nextHeadingPos);
      expect(section, `no Hint in ${code} section`).not.toContain("**Hint:**");
    }
  });

  it("starts with the generated-file comment", () => {
    const md = renderErrorsMarkdown();
    expect(md.startsWith("<!-- Generated by scripts/gen-errors.ts.")).toBe(true);
  });
});

describe("mapFsError", () => {
  it("translates ENOENT to FILE_NOT_FOUND", () => {
    const result = mapFsError({ code: "ENOENT", message: "no such file" }, "CONFIG_WRITE_FAILED");
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.code).toBe("FILE_NOT_FOUND");
      expect(result.error).toBe("no such file");
    }
  });

  it("uses the fallback code for non-ENOENT errors", () => {
    const result = mapFsError(new Error("disk full"), "CONFIG_WRITE_FAILED");
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.code).toBe("CONFIG_WRITE_FAILED");
      expect(result.error).toContain("disk full");
    }
  });
});

describe("docs/errors.md", () => {
  it("matches the catalog (run `bun run gen:errors` if this fails)", async () => {
    const path = resolve(import.meta.dir, "..", "..", "..", "docs", "errors.md");
    const onDisk = await readFile(path, "utf-8");
    const expected = renderErrorsMarkdown();
    expect(onDisk).toBe(expected);
  });
});
